### ISSUE TITLE
So when I compiled your driver ,How to use it through X ?

### ISSUE THREAD

**Issue by cuu** [libcg/mali#1]
Is there any tips show me how to use this driver in the newer mainline kernel? like 4.14.x ,etc
is this compatible with xf86-video-armsoc or ,just xf86-video-fbdev?

Thanks

**Comment by libcg** [comment]
Code is sourced from https://developer.arm.com/products/software/mali-drivers/utgard-kernel, I recommend you use their portal to get more information. This repo is heavily outdated now.
